DEBUG 2023-09-27 09:55:20.570 UTC: 	 CRAB Client version: v3.230612
DEBUG 2023-09-27 09:55:20.570 UTC: 	 Running on: Linux lxplus7108.cern.ch 3.10.0-1160.95.1.el7.x86_64 #1 SMP Mon Jul 24 13:59:37 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2023-09-27 09:55:20.570 UTC: 	 Executing command: 'submit'
DEBUG 2023-09-27 09:55:20.570 UTC: 	 Found CRAB cache file /afs/cern.ch/user/v/vavladim/.crab3
INFO 2023-09-27 09:55:20.571 UTC: 	 Will use CRAB configuration file crab_many_files.py
DEBUG 2023-09-27 09:55:20.571 UTC: 	 Loading CRAB configuration file.
DEBUG 2023-09-27 09:55:21.702 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2023-09-27 09:55:21.702 UTC: 	 Working area '/afs/cern.ch/user/v/vavladim/public/CMSSW_13_2_4/src/HeavyIonsAnalysis/Configuration/test/rho_test/crab_rho_test' already exists 
Please change the requestName in the config file
ERROR 2023-09-27 09:55:21.703 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/Commands/SubCommand.py", line 318, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/ClientUtilities.py", line 387, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/afs/cern.ch/user/v/vavladim/public/CMSSW_13_2_4/src/HeavyIonsAnalysis/Configuration/test/rho_test/crab_rho_test' already exists 
Please change the requestName in the config file
INFO 2023-09-27 09:55:21.741 UTC: 	 Log file is /afs/cern.ch/user/v/vavladim/public/CMSSW_13_2_4/src/HeavyIonsAnalysis/Configuration/test/crab.log
DEBUG 2023-09-27 15:18:11.148 UTC: 	 CRAB Client version: v3.230612
DEBUG 2023-09-27 15:18:11.148 UTC: 	 Running on: Linux lxplus750.cern.ch 3.10.0-1160.95.1.el7.x86_64 #1 SMP Mon Jul 24 13:59:37 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2023-09-27 15:18:11.148 UTC: 	 Executing command: 'resubmit'
DEBUG 2023-09-27 15:18:11.149 UTC: 	 Found CRAB cache file /afs/cern.ch/user/v/vavladim/.crab3
ERROR 2023-09-27 15:18:11.181 UTC: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/v/vavladim/public/CMSSW_13_2_4/src/HeavyIonsAnalysis/Configuration/test/rho_test
ERROR 2023-09-27 15:18:11.181 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/Commands/resubmit.py", line 30, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/Commands/SubCommand.py", line 275, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/Commands/SubCommand.py", line 646, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/Commands/SubCommand.py", line 508, in loadLocalCache
    raise ex
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/Commands/SubCommand.py", line 502, in loadLocalCache
    self.cachedinfo, self.logfile = loadCache(self.requestarea, self.logger)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/ClientUtilities.py", line 440, in loadCache
    raise CachefileNotFoundException(msg)
CRABClient.ClientExceptions.CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/v/vavladim/public/CMSSW_13_2_4/src/HeavyIonsAnalysis/Configuration/test/rho_test
INFO 2023-09-27 15:18:11.195 UTC: 	 Log file is /afs/cern.ch/user/v/vavladim/public/CMSSW_13_2_4/src/HeavyIonsAnalysis/Configuration/test/crab.log
DEBUG 2023-09-27 15:19:16.485 UTC: 	 CRAB Client version: v3.230612
DEBUG 2023-09-27 15:19:16.485 UTC: 	 Running on: Linux lxplus750.cern.ch 3.10.0-1160.95.1.el7.x86_64 #1 SMP Mon Jul 24 13:59:37 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2023-09-27 15:19:16.485 UTC: 	 Executing command: 'resubmit'
DEBUG 2023-09-27 15:19:16.485 UTC: 	 Found CRAB cache file /afs/cern.ch/user/v/vavladim/.crab3
ERROR 2023-09-27 15:19:16.488 UTC: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/v/vavladim/public/CMSSW_13_2_4/src/HeavyIonsAnalysis/Configuration/test/rho_test
ERROR 2023-09-27 15:19:16.488 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/Commands/resubmit.py", line 30, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/Commands/SubCommand.py", line 275, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/Commands/SubCommand.py", line 646, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/Commands/SubCommand.py", line 508, in loadLocalCache
    raise ex
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/Commands/SubCommand.py", line 502, in loadLocalCache
    self.cachedinfo, self.logfile = loadCache(self.requestarea, self.logger)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/ClientUtilities.py", line 440, in loadCache
    raise CachefileNotFoundException(msg)
CRABClient.ClientExceptions.CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/v/vavladim/public/CMSSW_13_2_4/src/HeavyIonsAnalysis/Configuration/test/rho_test
INFO 2023-09-27 15:19:16.491 UTC: 	 Log file is /afs/cern.ch/user/v/vavladim/public/CMSSW_13_2_4/src/HeavyIonsAnalysis/Configuration/test/crab.log
